version: '2'
services:
    dataintergration-app:
        image: dl-data-indexing
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://dataintergration-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=DataIntergration
            - SIMLIFE_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=dataintergration-elasticsearch:9300
        ports:
            - 8080:8080
    dataintergration-mongodb:
        extends:
            file: mongodb.yml
            service: dataintergration-mongodb
    dataintergration-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dataintergration-elasticsearch
