version: '2'
services:
    dataintergration-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        volumes:
            - ~/volumes/simlife/DataIntergration/mongodb/:/data/db/
